# Generated by Django 5.2.11 on 2026-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('categoria', models.CharField(choices=[('igreja', 'Igreja'), ('eventos', 'Eventos'), ('comunidade', 'Comunidade'), ('festas', 'Festas'), ('outros', 'Outros')], default='outros', max_length=15, verbose_name='categoria')),
                ('imagem', models.ImageField(upload_to='galeria/%Y/%m/', verbose_name='imagem original')),
                ('imagem_thumb', models.ImageField(blank=True, upload_to='galeria/thumbs/', verbose_name='miniatura')),
                ('imagem_medium', models.ImageField(blank=True, upload_to='galeria/medium/', verbose_name='média')),
                ('imagem_large', models.ImageField(blank=True, upload_to='galeria/large/', verbose_name='grande')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='data de upload')),
            ],
            options={
                'verbose_name': 'imagem da galeria',
                'verbose_name_plural': 'imagens da galeria',
                'ordering': ['-data_upload'],
            },
        ),
    ]
