# Generated by Django 5.2.11 on 2026-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail'), ('endereco', 'Endereço'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=15, verbose_name='tipo')),
                ('valor', models.CharField(max_length=300, verbose_name='valor')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='ícone (FontAwesome)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'informação de contato',
                'verbose_name_plural': 'informações de contato',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='dia da semana')),
                ('horario', models.TimeField(verbose_name='horário')),
                ('tipo', models.CharField(choices=[('missa', 'Missa'), ('missa_solene', 'Missa Solene'), ('adoracao', 'Adoração'), ('terco', 'Terço')], default='missa', max_length=15, verbose_name='tipo')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='nome/observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'horário de missa',
                'verbose_name_plural': 'horários de missas',
                'ordering': ['ordem', 'dia_semana', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='subtítulo')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('imagem', models.ImageField(blank=True, upload_to='noticias/%Y/%m/', verbose_name='imagem')),
                ('tipo', models.CharField(choices=[('noticia', 'Notícia'), ('evento', 'Evento'), ('aviso', 'Aviso')], default='noticia', max_length=10, verbose_name='tipo')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('chave', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='chave')),
                ('valor', models.TextField(verbose_name='valor')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=100, unique=True, verbose_name='seção')),
                ('titulo', models.CharField(max_length=500, verbose_name='título/valor')),
                ('conteudo', models.TextField(blank=True, verbose_name='conteúdo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'conteúdo do site',
                'verbose_name_plural': 'conteúdos do site',
                'ordering': ['ordem'],
            },
        ),
    ]
