# Generated by Django 5.2.11 on 2026-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
